version = 0.1

##############################################################################
# PRODUCTION Environment
##############################################################################
[default.deploy.parameters]
stack_name = "yallabalagan-newsletter-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-prod"
s3_prefix = "yallabalagan-newsletter"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=prod",
    "SenderEmail=newsletter@yourdomain.com"
]
confirm_changeset = true
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

##############################################################################
# DEVELOPMENT Environment
##############################################################################
[dev.deploy.parameters]
stack_name = "yallabalagan-newsletter-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dev"
s3_prefix = "yallabalagan-newsletter"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "SenderEmail=newsletter-dev@yourdomain.com"
]
confirm_changeset = false
image_repositories = []

[dev.build.parameters]
cached = true
parallel = true
